var quotes = [];
quotes.push("It could have been titled, \"The Elephant in the Room.\"<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/ecumenism/\">An Open Letter to Catholics on Orthodoxy and Ecumenism</a>");
quotes.push("It was originally written to communicate to Catholics, but there are some things there that Orthodox might need to hear, too.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/ecumenism/\">An Open Letter to Catholics on Orthodoxy and Ecumenism</a>");
quotes.push("At the end of his life, Thomas Aquinas said, \"All that I have written I consider as straw.\" And Orthodoxy begins where Thomas Aquinas left off.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/ecumenism/\">An Open Letter to Catholics on Orthodoxy and Ecumenism</a>");
quotes.push("Restoring harmony with nature as we know it is missing something. The spiritual reality reaches far deeper.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/exotic/\">Exotic Golden Ages and Restoring Harmony with Nature: Anatomy of a Passion</a>");
quotes.push("It is a great tragedy to overlook the here and now.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/exotic/\">Exotic Golden Ages and Restoring Harmony with Nature: Anatomy of a Passion</a>");
quotes.push("It's the one act the Bible calls holy.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/sacrament/\">The Eighth Sacrament</a>");
quotes.push("A microcosm of spiritual life.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/sacrament/\">The Eighth Sacrament</a>");
quotes.push("There is something about life that is too easy to forget.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/crown/\">Our Crown of Thorns</a>");
quotes.push("There can be something profoundly valuable about suffering.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/crown/\">Our Crown of Thorns</a>");
quotes.push("Can we ever escape shame?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/unashamed/\">Unashamed</a>");
quotes.push("There was a song, simple and pure.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/unashamed/\">Unashamed</a>");
quotes.push("<em>COMMENTARY<br />ON THE OLD AND NEW TESTAMENTS<br />IN ONE VOLUME<br />CONTAINING A CAREFUL ANALYSIS OF ALL CULTURAL ISSUES<br />NEEDFUL TO UNDERSTAND THE BIBLE<br />AS DID ITS FIRST READERS</em><br /><a target=\"_blank\" href=\"http://JonathansCorner.com/commentary/\">The Commentary</a>");
quotes.push("He found what he was looking for, and it utterly shocked him. What will studying the Bible's cultures <em>never</em> tell you?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/commentary/\">The Commentary</a>");
quotes.push("The spectrum of light split by a prism.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/christmas_tales/\">The Christmas Tales</a>");
quotes.push("They were snowbound, at least for a little while. What did they have to share?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/christmas_tales/\">The Christmas Tales</a>");
quotes.push("We say we have rights. Do we?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/no_rights/\">Do We Have Rights?</a>");
quotes.push("Rights have become so important to how we think that we've lost touch with many societies that get along well--<em>without</em> any real system of rights.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/no_rights/\">Do We Have Rights?</a>");
quotes.push("There are things about marriage that we miss if we think in terms of men and women.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/headship/\">What the Current Debate Won't Tell You About Headship</a>");
quotes.push("Men and women are part of something larger.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/headship/\">What the Current Debate Won't Tell You About Headship</a>");
quotes.push("Ever notice that pets have trouble learning even rules you intend for their good?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/pet/\">A Pet Owner's Rules</a>");
quotes.push("God is like a pet owner.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/pet/\">A Pet Owner's Rules</a>");
quotes.push("A paean of beauty.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/hymn/\">Hymn to the Creator of Heaven and Earth</a>");
quotes.push("Orthodox worship has always been connected to nature.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/hymn/\">Hymn to the Creator of Heaven and Earth</a>");
quotes.push("An icon may be a painting, but there's more than meets the eye.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/icons/\">Lesser Icons: Reflections on Faith, Icons, and Art</a>");
quotes.push("How do icons illuminate art?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/icons/\">Lesser Icons: Reflections on Faith, Icons, and Art</a>");
quotes.push("The Christian life has decisive moments. Including one you might not think of.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/decisive/\">Two Decisive Moments</a>");
quotes.push("\"When was the world created?\" is a trick question.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/decisive/\">Two Decisive Moments</a>");
quotes.push("It is amazing how much of life we fail to appreciate.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/life/\">A Wonderful Life</a>");
quotes.push("She had a very difficult life. And a very beautiful one.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/life/\">A Wonderful Life</a>");
quotes.push("They're called \"Windows of Heaven.\"<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/stephanos/\">Stephanos</a>");
quotes.push("\"The crown of earth is the temple, and the crown of the temple is Heaven.\"<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/stephanos/\">Stephanos</a>");
quotes.push("It seems Church Fathers can be cantankerous.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/athanasius/\">Athanasius: <em>On Creative Fidelity</em></a>");
quotes.push("Maybe \"creative fidelity\" wasn't such a breakthrough insight after all.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/athanasius/\">Athanasius: <em>On Creative Fidelity</em></a>");
quotes.push("The best things in life are free.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/money/\">Money</a>");
quotes.push("There are some things money can't buy.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/money/\">Money</a>");
quotes.push("I misunderstood basic things about Orthodoxy, too.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/calvinist/\">An Orthodox Looks at a Calvinist Looking at Orthodoxy</a>");
quotes.push("A Calvinist raises some natural questions about Orthodoxy.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/calvinist/\">An Orthodox Looks at a Calvinist Looking at Orthodoxy</a>");
quotes.push("The Allegory of the Cave, updated.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/plato/\">Plato: The Allegory of the... Flickering Screen?</a>");
quotes.push("Maybe it's just talking about television... but maybe it isn't.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/plato/\">Plato: The Allegory of the... Flickering Screen?</a>");
quotes.push("No, it isn't about magic.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/technonomicon/\">Technonomicon: Technology, Nature, Ascesis</a>");
quotes.push("There are things deeper than technology.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/technonomicon/\">Technonomicon: Technology, Nature, Ascesis</a>");
quotes.push("Sing to the Lord a new song.<br />Sing to the Lord, all the earth.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/doxology/\">Doxology</a>");
quotes.push("Who can tell of the glory of God?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/doxology/\">Doxology</a>");
quotes.push("A survival guide for a recession, depression, or economic collapse.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/survive/\">How to Survive an Economic Depression</a>");
quotes.push("Does faith have anything to do with how to survive hard times?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/survive/\">How to Survive an Economic Depression</a>");
quotes.push("It's about what's wrong with our ideas today about religion and science.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/religion-science/\">\"Religion and Science\" Is Not Just Intelligent Design vs. Evolution</a>");
quotes.push("Some theologians are concerned about not being scientific enough, but could the problem be that theology is TOO scientific?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/religion-science/\">\"Religion and Science\" Is Not Just Intelligent Design vs. Evolution</a>");
quotes.push("You cannot fathom how much God loves you.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/father/\">God the Spiritual Father</a>");
quotes.push("Would you like a glimpse into the Fatherhood of God?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/father/\">God the Spiritual Father</a>");
quotes.push("What is the maximum to have in life?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/maximum/\">Maximum Christ, Maximum Ambition, Maximum Repentance</a>");
quotes.push("Do you want more?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/maximum/\">Maximum Christ, Maximum Ambition, Maximum Repentance</a>");
quotes.push("Rejoice, O flowing fountain of Heaven's treasures!<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/philaret/\">Akathist to St. Philaret the Merciful</a>");
quotes.push("A saint who was abundantly generous when he had much, and then after losing almost everything, was abundantly generous out of the little he had left.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/philaret/\">Akathist to St. Philaret the Merciful</a>");
quotes.push("God offers mountains to climb and the strength for climbing.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/arena/\">The Arena</a>");
quotes.push("Saints and angels are watching our struggles, praying and cheering.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/arena/\">The Arena</a>");
quotes.push("There are wonders beyond our understanding.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/transcendent/\">The Transcendent God Who Approaches Us Through Our Neighbor</a>");
quotes.push("You cannot separate your neighbor from God.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/transcendent/\">The Transcendent God Who Approaches Us Through Our Neighbor</a>");
quotes.push("We want God to help us do better with the games in our lives. God wants to change the game.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/gamechanger/\">God the Game Changer</a>");
quotes.push("What can technologies like the iPhone tell us about God?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/gamechanger/\">God the Game Changer</a>");
quotes.push("The question was evil. Its answer was good.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/waste/\">Why this Waste?</a>");
quotes.push("The answer has many layers.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/waste/\">Why this Waste?</a>");
quotes.push("One of the most basic and important prayers in the Orthodox Church.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/jesus-prayer/\">An Introduction to the Jesus Prayer</a>");
quotes.push("A minute to begin, and a lifetime to grow into.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/jesus-prayer/\">An Introduction to the Jesus Prayer</a>");
quotes.push("It picks a Psalm. It may pick just the one you need.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/psalms/\">Psalm Picker</a>");
quotes.push("The Psalms are prayers at the heart of the Orthodox Church.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/psalms/\">Psalm Picker</a>");
quotes.push("In time of life, prepare for death.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/death/\">Death</a>");
quotes.push("If we are in denial as a society about death, then something very cliche is true: the first step to recovery is to stop denial.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/death/\">Death</a>");
quotes.push("We live in a labyrinth of a world.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/labyrinth/\"/>The Labyrinth</a>");
quotes.push("Labyrinths are not just long ago and far away.<br />We live in one.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/labyrinth/\"/>The Labyrinth</a>");
quotes.push("How shall I be open to thee,<br />O Lord who is forever open to me?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/open/\">Open</a>");
quotes.push("Incessantly I seek to clench with tight fist,<br />Such things as thou gavest mine open hand.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/open/\">Open</a>");
quotes.push("Save me from forging false gods, O Lord, and deliver me from the chains of passion I have entangled me in. Do thou raise mine eyes to Heaven, with my neck ever bowed to thee, and my hands open to thy grace and open to my neighbor. I have fallen: do thou raise me up, that I may praise and glorify thy name. Amen.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/prayers/\">Prayers</a>");
quotes.push("Give me thy Life, O Lord, and enlighten me with thy divine energies. Let my life be whole in all ways, and let me see thy Light. Have mercy on me in my sins, and rescue me from a world fallen twice: once as all men have fallen, and once again into a life moulded of plastic. Yea here and now let me live thy Life, and not some time I imagine in future circumstances; shew me thy glory and transfigure me. Lofty visions are beyond me: but in prayer and love for my neighbor allow me to participate in thy glory, thine eternal radiant splendor.  In the name of the Father of Lights, and the Son who was transfigured, and the Holy Spirit who illuminest, amen.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/prayers/\">Prayers</a>");
quotes.push("What is the chief end of human life?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/contemplation/\">Contemplation</a>");
quotes.push("We were made for the glory of contemplating God.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/contemplation/\">Contemplation</a>");
quotes.push("Incarnation does not stop with Christ's birth.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/deification/\">Incarnation and Deification</a>");
quotes.push("The reason why the Word became flesh.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/deification/\">Incarnation and Deification</a>");
quotes.push("The ordinary is overlooked.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/ordinary/\">Ordinary</a>");
quotes.push("Any fool can handle a crisis, or so it has been said. What really takes doing is handling ordinary life.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/ordinary/\">Ordinary</a>");
quotes.push("The Sermon on the Mount is a practical handbook for everyday life.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/yoke/\">A Yoke that is Easy and a Burden that is Light</a>");
quotes.push("Virtue is easy. Vice is hard.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/yoke/\">A Yoke that is Easy and a Burden that is Light</a>");
quotes.push("Letters fit for a king.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/royal/\">The Royal Letters</a>");
quotes.push("There is something royal about being human.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/royal/\">The Royal Letters</a>");
quotes.push("C.S. Lewis's That Hideous Strength describes real enough forces. But there is a yet greater strength.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/strength/\">That Beautiful Strength</a>");
quotes.push("Beauty triumphs over all.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/strength/\">That Beautiful Strength</a>");
quotes.push("Pleasure comes with a price tag.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/pleasure/\">The Pleasure-Pain Syndrome</a>");
quotes.push("Why do you chase after pleasures so much? Pleasure is laced with pain.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/pleasure/\">The Pleasure-Pain Syndrome</a>");
quotes.push("Fr. Seraphim (Rose)'s followers deny that their movement 'tastes like Kool-Aid' and they'll take a sledgehammer to anyone who disagrees.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/seraphim/\">What Makes Me Uneasy About Fr. Seraphim (Rose) and His Followers</a>");
quotes.push("An explanation of what a Russian Orthodox Christian might be bothered about in Fr. Seraphim (Rose) and his admirers.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/seraphim/\">What Makes Me Uneasy About Fr. Seraphim (Rose) and His Followers</a>");
quotes.push("Church Fathers often believed in a young earth. But none of them made it 'the article by which the Church stands or falls.'<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/creation/\">Creation and Holy Orthodoxy: Fundamentalism is Not Enough</a>");
quotes.push("Against Protestant Fundamentalist Orthodoxy.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/creation/\">Creation and Holy Orthodoxy: Fundamentalism is Not Enough</a>");
quotes.push("Who among us did not grow up to the beat of drums sounded by Narnia?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/narnia/\">A Pilgrimage from Narnia</a>");
quotes.push("To Narnia we say: Further in and further up!<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/narnia/\">A Pilgrimage from Narnia</a>");
quotes.push("Its first hearers were stunned. Should we expect to find it to be politically correct today?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/sermon/\">The Most Politically Incorrect Sermon in History: A Comment on the Sermon on the Mount</a>");
quotes.push("Anyone who has not been shocked by it has failed to understand it.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/sermon/\">The Most Politically Incorrect Sermon in History: A Comment on the Sermon on the Mount</a>");
quotes.push("Wishing the Fathers were compatible with evolution is as wishful thinking as good old Creation Science.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/evolution/\">Note to Orthodox Evolutionists: Stop Trying to Recruit / Shanghai the Fathers to Your Camp!</a>");
quotes.push("Wanting the Fathers to agree with evolution is fine. Distorting them is not.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/evolution/\">Note to Orthodox Evolutionists: Stop Trying to Recruit / Shanghai the Fathers to Your Camp!</a>");
quotes.push("The flaw of Narcissus is scarcely less prevalent than technology.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/pride/\">Pride</a>");
quotes.push("The sin by which Satan fell from Heaven.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/pride/\">Pride</a>");
quotes.push("Ecumenism is the ecclesiological heresy of our age.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/quotes/\">Twelve Quotes on Orthodoxy, Ecumenism, and Catholicism</a>");
quotes.push("Ecumenism: Invented by Protestants. Adapted by Catholics. Foisted on Orthodox. Won't you agree it smells fishy?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/quotes/\">Twelve Quotes on Orthodoxy, Ecumenism, and Catholicism</a>");
quotes.push("We were made for the divine glory!<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/glory/\">Glory</a>");
quotes.push("The Lord is King! He hath clothed himself in glory!<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/glory/\">Glory</a>");
quotes.push("The best things in life are free. Including suffering that we can grow by.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/best/\">The Best Things in Life Are Free</a>");
quotes.push("People say that the best things in life are free. What does that mean, really?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/best/\">The Best Things In Life Are Free</a>");
quotes.push("No, it's not light swearing.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/backswing/\">The Damned Backswing</a>");
quotes.push("Some things come with a nasty catch.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/backswing/\">The Damned Backswing</a>");
quotes.push("The author, Christos Jonathan Seth Hayward, lives to create treasure.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/treasure/\">Treasure</a>");
quotes.push("What is treasure?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/treasure/\">Treasure</a>");
quotes.push("A Swiss Army Knife is very impressive.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/swiss-army-knife/\">The Swiss Army Knife and God</a>");
quotes.push("Do Swiss Army Knives offer us any opportunity for understanding God?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/swiss-army-knife/\">The Swiss Army Knife and God</a>");
quotes.push("Our thoughts are befouled; we need the cleaning of silent prayer.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/lent/\">Take Your Shoes Off Your Feet, for the Place Where You Are Standing Is Holy Ground</a>");
quotes.push("The thoughts that stain us do not boil down to worldview.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/lent/\">Take Your Shoes Off Your Feet, for the Place Where You Are Standing Is Holy Ground</a>");
quotes.push("Feminism has all kinds of unclean communication: feminist fairy tales are manipulative propaganda and go against what a great many women believe.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/unman/\">Un-man's Tales: C.S. Lewis's 'Perelandra', Fairy Tales, and Feminism</a>");
quotes.push("In Martin Luther's day, people did not see how one could possibly be condemned by the Church and be right with God. Today people do not see how one could conceivably jettison feminism and advance women's best interests in the same act. But look at how feminism communicates: is THAT the sigil of truth?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/unman/\">Un-man's Tales: C.S. Lewis's 'Perelandra', Fairy Tales, and Feminism</a>");
quotes.push("Is there a fishy smell to Anglicans in the Western Rite?<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/oops/\">Oops... Could the Western Rite Please Try Again?</a>");
quotes.push("There's an uncanny resemblance to an Onion article, or at least that's how it opens.<br /><a target=\"_blank\" href=\"http://JonathansCorner.com/oops/\">Oops... Could the Western Rite Please Try Again?</a>");
document.getElementById("quotes").innerHTML = "<p><strong>From <a target='_blank' href='http://JonathansCorner.com/'>Jonathan's Corner</a>:</strong><br />" + quotes[Math.floor(Math.random() * quotes.length)] + "</p>";
